// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_rhxNCX-ca2Mmnk_Wl9txHg87xE2MGWM',
    appId: '1:314249489778:web:928b8f768e0970c7f101eb',
    messagingSenderId: '314249489778',
    projectId: 'loginmixue',
    authDomain: 'loginmixue.firebaseapp.com',
    storageBucket: 'loginmixue.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxydGT5DhQjqQEIrlUp7bU2XPbWaxl17w',
    appId: '1:314249489778:android:1dd2c3e802248ecff101eb',
    messagingSenderId: '314249489778',
    projectId: 'loginmixue',
    storageBucket: 'loginmixue.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV4p3aJ_OQ3xl50j5ivjIZMChr8dOEIic',
    appId: '1:314249489778:ios:942f6e14cdfb4d50f101eb',
    messagingSenderId: '314249489778',
    projectId: 'loginmixue',
    storageBucket: 'loginmixue.appspot.com',
    iosBundleId: 'com.example.mixuee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV4p3aJ_OQ3xl50j5ivjIZMChr8dOEIic',
    appId: '1:314249489778:ios:3c38d166bd7a508df101eb',
    messagingSenderId: '314249489778',
    projectId: 'loginmixue',
    storageBucket: 'loginmixue.appspot.com',
    iosBundleId: 'com.example.mixuee.RunnerTests',
  );
}
